### ISSUE TITLE
SerializationException on ListField ViewModels

### ISSUE THREAD

**Issue by SchelstraeteRuben** [bartverdonck/Sitecore-Forms-Extensions#115]
We recently upgraded to SFE 3.1 on Sitecore 9.3.

After deploying this to production (2 CD nodes & shared session management in a sql session db), we noticed this exception occurring sometimes: 

> Unable to serialize the session state. In 'StateServer' and 'SQLServer' mode, ASP.NET will serialize the session state objects, and as a result non-serializable objects or MarshalByRef objects are not permitted. The same restriction applies if similar serialization is done by the custom session state store in 'Custom' mode. Type 'Feature.FormsExtensions.Fields.Bindings.ListWithBindingsViewModel' in Assembly 'Feature.FormsExtensions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

> System.Web.HttpException:
   at System.Web.Util.AltSerialization.WriteValueToStream (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Web.SessionState.SessionStateItemCollection.WriteValueToStreamWithAssert (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Web.SessionState.SessionStateItemCollection.Serialize (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at Sitecore.SessionProvider.SessionStateSerializer.Serialize (Sitecore.SessionProvider, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Sitecore.SessionProvider.SessionStateSerializer.Compress (Sitecore.SessionProvider, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Sitecore.SessionProvider.SessionStateSerializer.Serialize (Sitecore.SessionProvider, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Sitecore.SessionProvider.Sql.SqlSessionStateStore.UpdateAndReleaseItem (Sitecore.SessionProvider.Sql, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Sitecore.SessionProvider.Sql.SqlSessionStateProvider.SetAndReleaseItemExclusive (Sitecore.SessionProvider.Sql, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Web.SessionState.SessionStateModule.OnReleaseState (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Web.HttpApplication+SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Web.HttpApplication+<>c__DisplayClass285_0.<ExecuteStepImpl>b__0 (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Web.HttpApplication.ExecuteStepImpl (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Web.HttpApplication.ExecuteStep (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
Inner exception System.Runtime.Serialization.SerializationException handled at System.Web.Util.AltSerialization.WriteValueToStream:
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Web.Util.AltSerialization.WriteValueToStream (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)

I noticed that the following viewmodel classes don't have the [Serializable] attribute which I believe is necessary. 

- CheckBoxListWithBindingsViewModel
- DropDownWithBindingsViewModel
- ListBoxWithBindingsViewModel
- ListWithBindingsViewModel

So I think the fix here is obvious, and the attributes need to be added. But an additional question: Do you know why these objects are serialized in the sessionstate? 

Kind regards,
Ruben

**Comment by peng-qd** [comment]
We are experiencing the same error. The environment is SFE 3.2, Sitecore 9.3 on CD (using Redis as session provider). The error is below:

9648 00:10:22 ERROR SetAndReleaseItemExclusive => System.Runtime.Serialization.SerializationException: Type 'Feature.FormsExtensions.Fields.Bindings.DropDownWithBindingsViewModel' in Assembly 'Feature.FormsExtensions, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(WriteObjectInfo objectInfo, NameInfo arrayElemTypeNameInfo, Object data)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(WriteObjectInfo objectInfo, NameInfo memberNameInfo, WriteObjectInfo memberObjectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at Sitecore.SessionProvider.Redis.BinarySerializer.Serialize(Object data, Boolean compress)
   at Sitecore.SessionProvider.Redis.RedisUtility.AppendUpdatedOrNewItemsInList(ChangeTrackingSessionStateItemCollection sessionItems, List`1 list, Boolean compress)
   at Sitecore.SessionProvider.Redis.RedisConnectionWrapper.TryUpdateIfLockIdMatchPrepare(String sessionId, Object lockId, ISessionStateItemCollection data, Int32 sessionTimeout, String[]& keyArgs, Object[]& valueArgs)
   at Sitecore.SessionProvider.Redis.RedisConnectionWrapper.TryUpdateAndReleaseLockIfLockIdMatch(String sessionId, Object lockId, ISessionStateItemCollection data, Int32 sessionTimeout)
   at Sitecore.SessionProvider.Redis.RedisSessionStateProvider.SetAndReleaseItemExclusive(HttpContext context, String id, SessionStateStoreData item, Object lockId, Boolean newItem)
9648 00:10:22 ERROR Application error.
Exception: System.Runtime.Serialization.SerializationException
Message: Type 'Feature.FormsExtensions.Fields.Bindings.DropDownWithBindingsViewModel' in Assembly 'Feature.FormsExtensions, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
Source: mscorlib
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(WriteObjectInfo objectInfo, NameInfo arrayElemTypeNameInfo, Object data)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(WriteObjectInfo objectInfo, NameInfo memberNameInfo, WriteObjectInfo memberObjectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at Sitecore.SessionProvider.Redis.BinarySerializer.Serialize(Object data, Boolean compress)
   at Sitecore.SessionProvider.Redis.RedisUtility.AppendUpdatedOrNewItemsInList(ChangeTrackingSessionStateItemCollection sessionItems, List`1 list, Boolean compress)
   at Sitecore.SessionProvider.Redis.RedisConnectionWrapper.TryUpdateIfLockIdMatchPrepare(String sessionId, Object lockId, ISessionStateItemCollection data, Int32 sessionTimeout, String[]& keyArgs, Object[]& valueArgs)
   at Sitecore.SessionProvider.Redis.RedisConnectionWrapper.TryUpdateAndReleaseLockIfLockIdMatch(String sessionId, Object lockId, ISessionStateItemCollection data, Int32 sessionTimeout)
   at Sitecore.SessionProvider.Redis.RedisSessionStateProvider.SetAndReleaseItemExclusive(HttpContext context, String id, SessionStateStoreData item, Object lockId, Boolean newItem)
   at System.Web.SessionState.SessionStateModule.OnReleaseState(Object source, EventArgs eventArgs)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by peng-qd** [comment]
Thanks @SchelstraeteRuben , we are having the same issue when installing the SFE 3.2 in our Sitecore 9.3 CD environment. Have you managed a fix in your forked branch? I am having some trouble to generate a new package...much appreciated.

**Comment by SchelstraeteRuben** [comment]
@peng-qd,
Thanks or the reply. We are currently still looking for a repro scenario. Did you find one? 
We are also still investigating if this error prevents a form from being submitted, perhaps you know this as well? 

Kind regards,
Ruben

**Comment by peng-qd** [comment]
@SchelstraeteRuben , we installed the 3.2 version of SFE (which is the latest for Sc9.3). So i rebased the master branch to this commit: https://github.com/bartverdonck/Sitecore-Forms-Extensions/commit/22f1eb5e64d6f34a954a2c1f687e08d8ff812d42, and then add the "[Serializable]" attribute to the classes you mentioned. just rebuilt the project and dropped the  Feature.FormsExtensions.dll separately. The error went away. 
Also, before implement this change, the form actually submitted, i can see the email was sent and data was saved, it just showed a popup and not redirected to the success page.

**Comment by SchelstraeteRuben** [comment]
@peng-qd,

Thanks a lot for the feedback. How did you reproduce the issue?

Kind regards

**Comment by markgibbons25** [comment]
This issue will occur if you have Redis/SQL session state enabled.

**Comment by peng-qd** [comment]
@markgibbons25 was right. We are using Redis as the session provider.

**Comment by SchelstraeteRuben** [comment]
@markgibbons25 @peng-qd ,

We notice in the logs that this exception doesn't occur every time, sometimes the same form throws this error, sometimes it's submitted succesfully. Is this the same behaviour as you observed? It seems that the session isn't always serialized, but only in certain flows.

How did you reproduce this issue locally or on test environments? Currently we have only observed this issue on PRD and didn't manage to reproduce this on DEV/QA.

**Comment by SchelstraeteRuben** [comment]
@bartverdonck I created a PR that should fix this problem.

**Comment by bartverdonck** [comment]
Thanks for the push Ruben.

**Comment by bartverdonck** [comment]
4.0.2 released containing the fix

**Comment by SchelstraeteRuben** [comment]
Hi @bartverdonck ,

Thanks a lot for approving. Any chance this fix can be merged & released into the 3.2 (for Sitecore 9.3) version of the SFE as well? 

Kind regards,
Ruben

**Comment by SchelstraeteRuben** [comment]
Hi @bartverdonck , A kind reminder for my previous comment. Any chance this fix will be merged into 3.2 as well?

**Comment by Sumo20** [comment]
hi @bartverdonck
I still don't see a fix for this on 3.2, but it is in 4.01
