### ISSUE TITLE
 A task was canceled.

### ISSUE THREAD

**Issue by nalankaruppaiah** [bartverdonck/Sitecore-Forms-Extensions#48]
Hello,
First i would like to thank you for the beautiful module. 
We get this error intermittently when we submit the form. We have Recaptcha included. Appreciate if you could help us on this.

Source: mscorlib
Message: A task was canceled.
Stacktrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Feature.FormsExtensions.Business.ReCaptcha.ReCaptchaService.<Verify>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Feature.FormsExtensions.Business.ReCaptcha.AsyncHelpers.RunSync[T](Func`1 func)
   at Feature.FormsExtensions.Business.ReCaptcha.ReCaptchaService.VerifySync(String response)

**Comment by markgibbons25** [comment]
Looks like a network issue. Perhaps that code can be wrapped with Polly to retry?

**Comment by bartverdonck** [comment]
Good suggestion, but I like to avoid adding more dependencies to libraries. We could also add a try catch if the call fails, but then what to do, validate as "ok" anyway, or reject the validation.
