### ISSUE TITLE
Send email to fixed address: ERROR An item with the same key has already been added.

### ISSUE THREAD

**Issue by MokoPolo** [bartverdonck/Sitecore-Forms-Extensions#54]
I have a form that is trying to end email to fixed address and when I hit submit I get exception:

18192 22:01:20 ERROR An item with the same key has already been added.
Exception: System.ArgumentException
Message: An item with the same key has already been added.
Source: mscorlib
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Feature.FormsExtensions.SubmitActions.SendEmail.SendEmailBase`1.BuildCustomTokens(T data, FormSubmitContext formSubmitContext)
   at Feature.FormsExtensions.SubmitActions.SendEmail.SendEmailExtended.BuildCustomTokens(SendEmailExtendedData data, FormSubmitContext formSubmitContext)
   at Feature.FormsExtensions.SubmitActions.SendEmail.SendEmailBase`1.Execute(T data, FormSubmitContext formSubmitContext)

What am I doing wrong?

**Comment by bartverdonck** [comment]
Hi, you probably have 2 or multiple fields with the same name/id.

I will add a check in the code to avoid a crash.

**Comment by shobhatenkayilu** [comment]
> Hi, you probably have 2 or multiple fields with the same name/id.
> I will add a check in the code to avoid a crash.

Hi iam also facing same issue when the file upload  field is  added with pdf.

I have captcha and file upload  fields in the form.
When iam uploading any file to file upload field,the  form submits without any error.
But when I add file using field upload field,  Post formbuider error I get saying
An item with same key already present.
Please provide latest code url which I can download which has fixed this issue.
Thank in advance
