### ISSUE TITLE
Improve error handling for broken StringListInputs

### ISSUE THREAD

**Issue by sebastianlay** [bartverdonck/Sitecore-Forms-Extensions#93]
We had an issue with an improperly published form (that contained a dropdown field) which lead to the following error in the email submit action:

```
ERROR Index and count must refer to a location within the string.
Parameter name: count
Exception: System.ArgumentOutOfRangeException
Message: Index and count must refer to a location within the string.
Parameter name: count
Source: mscorlib
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Feature.FormsExtensions.Fields.ValueResolvers.StringValueFromStringListInputViewModelReader.Process(GetStringValueFromViewModelArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, Boolean failIfNotExists)
   at Feature.FormsExtensions.Fields.ValueResolvers.FormsFieldValueResolver.GetStringFieldValue(IViewModel fieldViewModel)
   at Feature.FormsExtensions.SubmitActions.SendEmail.Tokens.MailTokenBuilder.GetFieldValue(FormSubmitContext formSubmitContext, String fieldId)
   at Feature.FormsExtensions.SubmitActions.SendEmail.Tokens.MailTokenBuilder.BuildTokens(IDictionary`2 fieldTokens, FormSubmitContext formSubmitContext)
   at Feature.FormsExtensions.SubmitActions.SendEmail.SendEmailExtended.BuildCustomTokens(SendEmailExtendedData data, FormSubmitContext formSubmitContext)
   at Feature.FormsExtensions.SubmitActions.SendEmail.SendEmailBase`1.Execute(T data, FormSubmitContext formSubmitContext)
```

This error is thrown by the following code when `listStringInputViewModel.Value` is null (which does not seem to be checked):

https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/86f795100a5f3b94ec3b96db1d4e3528a6ace39d/src/Feature/FormsExtensions/code/Fields/ValueResolvers/StringValueFromStringListInputViewModelReader.cs#L8-L18

It would be nice if the error handling could be improved here so that the website visitor sees an error message. Alternatively the code could fail silently like it does for the `StringInput`:

https://github.com/bartverdonck/Sitecore-Forms-Extensions/blob/86f795100a5f3b94ec3b96db1d4e3528a6ace39d/src/Feature/FormsExtensions/code/Fields/ValueResolvers/StringValueFromStringInputViewModelReader.cs#L12

**Comment by bartverdonck** [comment]
add null check
